In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(a[:, 2])

[3 6 9]


In [4]:
a[0]

array([1, 2, 3])

In [5]:
print(a[:, 1])

[2 5 8]


In [6]:
a = np.array([
       [[10, 11, 12], [13, 14, 15], [16, 17, 18]], # matrix 0
       [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
       [[30, 31, 32], [33, 34, 35], [36, 37, 38]]
])

# sélectionne la deuxième matrice
a[1]

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [7]:
# On souhaite avoir 14 24 34 
x, y, z = a[:, 1, 1]

print(x, y, z)

14 24 34


In [8]:
a = np.array([
       [[10, 11, 12], [13, 14, 15], [16, 17, 18]], # matrix 0
       [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
       [[30, 31, 32], [33, 34, 35], [36, 37, 38]]
])

a.sum(0)

array([[60, 63, 66],
       [69, 72, 75],
       [78, 81, 84]])

In [9]:
a*2

array([[[20, 22, 24],
        [26, 28, 30],
        [32, 34, 36]],

       [[40, 42, 44],
        [46, 48, 50],
        [52, 54, 56]],

       [[60, 62, 64],
        [66, 68, 70],
        [72, 74, 76]]])

In [10]:
# 01 Exercice

In [11]:
x1 = np.array([[9, 1, 2],
       [8, 0, 2],
       [5, 1, 5]])

In [19]:
print( x1[0] )
print( x1[1] )
print( x1[2] )

[9 1 2]
[8 0 2]
[5 1 5]


In [20]:
# La deuxième colonne
print( x1[:, 1] )

# La première colonne
print( x1[:, 0] )

# La dernière colonne
print( x1[:, 1] )

[1 0 1]
[9 8 5]
[1 0 1]


In [26]:
"""
9 1 
8 0
"""
print( x1[:2,:2] )

[[9 1]
 [8 0]]


In [27]:
"""
0 2
1 5
"""
# start:end:step
print(x1[1:,1:])

[[0 2]
 [1 5]]


In [30]:
# Somme des lignes
x1.sum(1)

array([12, 10, 11])

In [32]:
# Somme des colonnes
x1.sum(0)

array([22,  2,  9])

In [35]:
# Somme des colonnes
x, y, z = x1.sum(0)
print(x, y, z)

# Somme des lignes
a, b, c = x1.sum(1)

print(a, b, c)

22 2 9
12 10 11


In [38]:
# 02 Exercice
x2 = np.array([ 
    [ [8, 4],[8, 9] ],
    [ [3, 0],[5, 0] ] 
])

print(x2)

[[[8 4]
  [8 9]]

 [[3 0]
  [5 0]]]


In [66]:
"""
8
8
"""

print( x2[0][:, 0] )

[8 8]


In [68]:
"""
4
9
"""

print( x2[0][:, 1] )

[4 9]


In [70]:
"""
0
0
"""

print( x2[1][:, 1] )

[0 0]


In [72]:
# 03 Exercice
a = np.array([
       [[10, 11, 12], [13, 14, 15], [16, 17, 18]], # matrix 0
       [[20, 21, 22], [23, 24, 25], [26, 27, 28]],
       [[30, 31, 32], [33, 34, 35], [36, 37, 38]]
])

print(a)

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]]]


In [73]:
"""
10 11 12
20 21 22
30 31 32
"""

'\n10 11 12\n20 21 22\n'